DEBUG 2021-10-22 15:29:50,043 minitest.py _miniSetUp      655 =========Current caseï¼štest_case_01=========
INFO  2021-10-22 15:29:50,045 app.py     relaunch        301 ReLaunch: /commonPage/logo/logo
DEBUG 2021-10-22 15:29:50,048 connection.py send            183 SEND > {"id":"713978fa-6a86-4ef4-9a88-dd4c69d843fa","method":"App.callWxMethod","params":{"method":"reLaunch","args":[{"url":"/commonPage/logo/logo"}]}}
DEBUG 2021-10-22 15:29:50,292 connection.py _on_message     232 RECV < {"id":"713978fa-6a86-4ef4-9a88-dd4c69d843fa","result":{"result":{"errMsg":"reLaunch:ok"}}}
DEBUG 2021-10-22 15:29:54,952 connection.py _on_message     232 RECV < {"method":"App.bindingCalled","params":{"name":"onAppRouteDone","args":[{"webviewId":5,"path":"page_ji_shi/qiangDan/qiangDan","query":{},"openType":"switchTab"},1634887794949]}}
INFO  2021-10-22 15:29:54,962 app.py     _on_route_changed 446 Route changed, {'name': 'onAppRouteDone', 'args': [{'webviewId': 5, 'path': 'page_ji_shi/qiangDan/qiangDan', 'query': {}, 'openType': 'switchTab'}, 1634887794949]}
WARNI 2021-10-22 15:29:54,962 app.py     relaunch        304 ReLaunch(/commonPage/logo/logo) but(/page_ji_shi/qiangDan/qiangDan)
INFO  2021-10-22 15:29:54,968 minitest.py capture         898 capture setup.png
DEBUG 2021-10-22 15:29:54,970 connection.py send            183 SEND > {"id":"f4fbd53e-0ed1-4dbc-b11f-cfd8479bb787","method":"App.captureScreenshot","params":{}}
DEBUG 2021-10-22 15:30:55,487 minitest.py _miniTearDown   862 =========Current case Downï¼štest_case_01=========
INFO  2021-10-22 15:30:55,492 minitest.py capture         898 capture teardown.png
DEBUG 2021-10-22 15:30:55,494 connection.py send            183 SEND > {"id":"1c617a64-3d3c-428b-9444-20960e0354ed","method":"App.captureScreenshot","params":{}}
ERROR 2021-10-22 15:31:56,105 minitest.py _miniTearDown   874 [call App.captureScreenshot] receive from remote timeout, id: 1c617a64-3d3c-428b-9444-20960e0354ed
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\framework\minitest.py", line 870, in _miniTearDown
    self.capture("teardown")
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\framework\minitest.py", line 899, in capture
    self.native.screen_shot(path)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\native\wx_native\idenative.py", line 28, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\app.py", line 131, in screen_shot
    b64_data = self.connection.send("App.captureScreenshot").get("result").get("data")
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\connection.py", line 185, in send
    return self._receive_response(cmd)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\connection.py", line 214, in _receive_response
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: [call App.captureScreenshot] receive from remote timeout, id: 1c617a64-3d3c-428b-9444-20960e0354ed
ERROR 2021-10-22 15:31:56,157 assertbase.py _teardown_collect 265 <bound method DemoTest.test_case_01 of <Demo.DemoTest testMethod=test_case_01>>
Traceback (most recent call last):
  File "D:\Python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\framework\libs\unittest\case.py", line 73, in run
    self._miniSetUp()
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\framework\minitest.py", line 666, in _miniSetUp
    self.capture("setup")
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\framework\minitest.py", line 899, in capture
    self.native.screen_shot(path)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\native\wx_native\idenative.py", line 28, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\minium_log.py", line 135, in wrapper
    result = func(*args, **kwargs)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\app.py", line 131, in screen_shot
    b64_data = self.connection.send("App.captureScreenshot").get("result").get("data")
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\connection.py", line 185, in send
    return self._receive_response(cmd)
  File "D:\Python\lib\site-packages\minium-1.2.1-py3.9.egg\minium\miniprogram\base_driver\connection.py", line 214, in _receive_response
    raise MiniTimeoutError(
minium.framework.exception.MiniTimeoutError: [call App.captureScreenshot] receive from remote timeout, id: f4fbd53e-0ed1-4dbc-b11f-cfd8479bb787
